baseURL: https://iasad.me/
languageCode: en-us
title: AsAd
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true
enableEmoji: true
pygmentsUseClasses: false

menu:
  main:
    - identifier: Root
      name: Root
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about
      weight: 15
    - identifier: Blogs
      name: Blogs
      url: /blogs
      weight: 20
    - identifier: Write-ups
      name: Write-ups
      url: /write-ups
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes

params:
  # theme
  env: production
  title: Asad Ullah
  description: "Tech enthusiast, blogger, and CTF player with a passion for cybersecurity. Sharing write-ups and insights on the latest tech trends and cybersecurity challenges. Follow along for engaging content"
  keywords: [Blog, Portfolio, PaperMod, iasad, iasad.me, "asad ullah", asadse7en]
  # author: Me
  # images: [""]
  dateFormat: "January 2, 2006"
  defaultTheme: dark #auto, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  hideFooter: false
  comments: true

  mainSections:
    - blogs
    - write-ups


  label:
    text: "./asadse7en"
    icon: "home/c.png"
    iconHeight: 35

  
  analytics:
    google:
      SiteVerificationTag: ""
    bing:
      SiteVerificationTag: ""
    yandex:
      SiteVerificationTag: ""


  # for enchanced SEO
  env: production

  homeInfoParams:
    Title: "Hi there,ğŸ‘‹"
    Content: >
      I'm **Asad Ullah**, a final year undergrad majoring **computer science** with focus on **security**ğŸ”’. This website serves as my **personal portfolio** for [***write-ups***](write-ups) âœ¨, and I will also be sharing [***blogs***](blog)âœï¸ on topics that pique my interest ğŸ¤”.
  # Home Page
  socialIcons:
    - name: "email"
      url: "mailto:asadse7en@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/asadse7en"
    - name: "github"
      url: "https://github.com/asadse7en"
    - name: "instagram"
      url: "https://www.instagram.com/iasadse7en"
    - name: "cv"
      url: "https://drive.google.com/file/d/1HS2k1c1RvtG7S-j_T7MZcQO2y1aHg6uH/view?usp=sharing"
    - name: "RSS"
      url: "https://iasad.me/index.xml"

  profileMode:
    enabled: false
    title: "Asad Ullah"
    subtitle: "Hello there!ğŸ‘‹ I'm **Asad**, a final year undergrad majoring in **computer science** with a focus on **security** ğŸ”’. This website serves as my **personal portfolio** for [***write-ups***](write-ups)âœ¨, and I'll also be sharing [***blogs***](blog)âœï¸ on topics that pique my interest ğŸ¤”."
    #imageUrl: "home/me.jpg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Me!


    

  # List View


  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: false
    linkFullImages: false

  editPost:
    URL: "https://github.com/asadse7en/iasad.me/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link


  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


  
# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true



markup:
  highlight:
    style: monokai
